from __future__ import annotations

import shutil
import zipfile
from pathlib import Path

from .util import slugify


INCLUDE_FILES = [
    "00-Bid-Scope-Summary.md",
    "01-Takeoff-Worksheet-REV1.xlsx",
    "02 - Proposal Letter.md",
    "scope-pages.pdf",
    "spec-pages.pdf",
    "takeoff/review-pages.md",
    "ALERTS.md",
]


def package_sendoff(project: Path, *, name: str | None = None) -> tuple[Path, Path]:
    project = project.resolve()
    work = project / "bid-package-working"
    sendoff_root = work / "supplier-sendoff"
    package_name = name or f"{slugify(project.name)}-supplier-sendoff"
    out_dir = sendoff_root / package_name
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    copied: list[str] = []
    for rel in INCLUDE_FILES:
        src = work / rel
        if src.exists() and src.is_file():
            dst = out_dir / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            copied.append(rel)

    image_dir = work / "page-images"
    if image_dir.exists():
        dst = out_dir / "page-images"
        shutil.copytree(image_dir, dst)
        copied.append("page-images/")

    readme = [
        f"# Supplier Sendoff - {project.name}",
        "",
        "This package was generated by contractor-bid.",
        "",
        "## Included Files",
        "",
    ]
    readme += [f"- `{item}`" for item in copied] or ["- No files were available to copy."]
    readme += [
        "",
        "## Review Note",
        "",
        "Confirm quantities, exclusions, alternates, and latest addendum basis before issuing pricing.",
        "",
    ]
    (out_dir / "README.md").write_text("\n".join(readme), encoding="utf-8")

    zip_path = sendoff_root / f"{package_name}.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for path in out_dir.rglob("*"):
            if path.is_file():
                zf.write(path, path.relative_to(out_dir.parent))
    return out_dir, zip_path
